# Generated by Django 2.2 on 2020-08-12 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('tee_color', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('rating', models.IntegerField()),
                ('slope', models.IntegerField()),
                ('par', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='quotes_liked', to='login_reg_app.User')),
                ('quote_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_posted', to='login_reg_app.User')),
            ],
        ),
    ]
