# Generated by Django 2.2 on 2020-08-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcp_calc', '0003_auto_20200816_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='diff',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='handicap',
            name='handicap_index',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
